[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>",
          "Denys Vitali <denys@denv.it>"]
name = "poppler"
license = "GPL-2.0"
version = "0.3.0"
description = "Wrapper for the GPL-licensed Poppler PDF rendering library."
repository = "https://github.com/DMSrs/poppler-rs"
edition = "2018"

[dependencies]
cairo-rs = { version= "0.8.0", features = ["png", "pdf"]}
cairo-sys-rs = "0.9.2"
glib = "0.9.1"
glib-sys = "0.9.1"
gobject-sys = "0.9.1"
